# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('url', models.CharField(max_length=50, verbose_name='Link/URL')),
                ('summary', models.TextField(max_length=100, verbose_name='Resumo')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
