# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='url',
            field=models.URLField(max_length=150, verbose_name='Link/URL'),
        ),
    ]
